### ISSUE TITLE
Absolute sizes == :( 

### ISSUE THREAD

**Issue by duckinator** [kn0ll/github-mobile#1]
Setting the width of `#content .page` to `<something>px` as you do adds a horizontal scrollbar on desktops, and it simply runs off the side of the page on an iPod Touch (entirely unaccessible -- i can't zoom out OR scroll to it).

Setting the height to `<something>px` makes it so the scrollbar goes behind the bottom bar of Mobile Safari, but this is negligible compared to the former problem.

**Comment by kn0ll** [comment]
interesting. this line should be taking care of it to some extent: https://github.com/catshirt/github-mobile/blob/master/public/js/lib/jquery.pages.js#L25 at the very least, it should all be visible. that said, i did notice similar weirdness with scrollbars (vertical and horizontal), so definitely need to revisit this. thanks!!!

**Comment by duckinator** [comment]
It's all visible now, but did you see what happens if you set it to 100% there?

100% fixed it on the desktop, and the way you have atm there's 0px of whitespace between the text and right side, which is _better_ but still not _good_.

**Comment by duckinator** [comment]
Also, I lied. Using a browser with proper fullscreen magic, the bottom is not visible due to the vertical height thing.
